In [3]:
import pandas as pd
import os
import requests

C:\Users\imaia\Anaconda3\lib\site-packages\requests\__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.3) or chardet (4.0.0) doesn't match a supported version!
  RequestsDependencyWarning)

In [23]:
token = "pk_8461a849e72a477296d96c3b9c8ecd2f"

base_url = 'https://cloud.iexapis.com/v1'

resp = requests.get(base_url + '/status')

resp

## historical price data for Apple

In [24]:
params = {'token': token}

apple_historical = requests.get(base_url+'/stock/AAPL/chart', params=params)

In [27]:

apple_historical

df = pd.DataFrame(apple_historical.json())

df

,change,changeOverTime,changePercent,close,date,fClose,fHigh,fLow,fOpen,fVolume,...,open,subkey,symbol,uClose,uHigh,uLow,uOpen,uVolume,updated,volume
0,0.000,0.000000,0.0000,135.390,2021-02-10,135.390,136.9900,134.4000,136.48,73046563,...,136.48,,AAPL,135.390,136.9900,134.4000,136.48,73046563,1613015280000,73046563
1,-0.260,-0.001920,-0.0019,135.130,2021-02-11,135.130,136.3900,133.7700,135.90,64280029,...,135.90,,AAPL,135.130,136.3900,133.7700,135.90,64280029,1613094482000,64280029
2,0.240,-0.000148,0.0018,135.370,2021-02-12,135.370,135.5300,133.6921,134.35,60145130,...,134.35,,AAPL,135.370,135.5300,133.6921,134.35,60145130,1613182566000,60145130
3,-2.180,-0.016249,-0.0161,133.190,2021-02-16,133.190,136.0100,132.7900,135.49,80576316,...,135.49,,AAPL,133.190,136.0100,132.7900,135.49,80576316,1613527203000,80576316
4,-2.350,-0.033607,-0.0176,130.840,2021-02-17,130.840,132.2200,129.4700,131.25,98085249,...,131.25,,AAPL,130.840,132.2200,129.4700,131.25,98085249,1613616486000,98085249
5,-1.130,-0.041953,-0.0086,129.710,2021-02-18,129.710,129.9950,127.4100,129.20,96856748,...,129.20,,AAPL,129.710,129.9950,127.4100,129.20,96856748,1613700057000,96856748
6,0.160,-0.040771,0.0012,129.870,2021-02-19,129.870,130.7100,128.8000,130.24,87668834,...,130.24,,AAPL,129.870,130.7100,128.8000,130.24,87668834,1613787364000,87668834
7,-3.870,-0.069355,-0.0298,126.000,2021-02-22,126.000,129.7200,125.6000,128.01,103916419,...,128.01,,AAPL,126.000,129.7200,125.6000,128.01,103916419,1614056406000,103916419
8,-0.140,-0.070389,-0.0011,125.860,2021-02-23,125.860,126.7100,118.3900,123.76,158273022,...,123.76,,AAPL,125.860,126.7100,118.3900,123.76,158273022,1614132001000,158273022
9,-0.510,-0.074156,-0.0041,125.350,2021-02-24,125.350,125.5600,122.2300,124.94,111039904,...,124.94,,AAPL,125.350,125.5600,122.2300,124.94,111039904,1614218401000,111039904
10,-4.360,-0.106359,-0.0348,120.990,2021-02-25,120.990,126.4585,120.5400,124.68,148199540,...,124.68,,AAPL,120.990,126.4585,120.5400,124.68,148199540,1614306723000,148199540
11,0.270,-0.104365,0.0022,121.260,2021-02-26,121.260,124.8500,121.2000,122.59,164560394,...,122.59,,AAPL,121.260,124.8500,121.2000,122.59,164560394,1614392164000,164560394
12,6.530,-0.056134,0.0539,127.790,2021-03-01,127.790,127.9300,122.7900,123.75,116307892,...,123.75,,AAPL,127.790,127.9300,122.7900,123.75,116307892,1614651363000,116307892
13,-2.670,-0.075855,-0.0209,125.120,2021-03-02,125.120,128.7200,125.0100,128.41,102260945,...,128.41,,AAPL,125.120,128.7200,125.0100,128.41,102260945,1614736807000,102260945
14,-3.060,-0.098456,-0.0245,122.060,2021-03-03,122.060,125.7100,121.8400,124.81,112966340,...,124.81,,AAPL,122.060,125.7100,121.8400,124.81,112966340,1614823212000,112966340
15,-1.930,-0.112711,-0.0158,120.130,2021-03-04,120.130,123.6000,118.6200,121.75,178154975,...,121.75,,AAPL,120.130,123.6000,118.6200,121.75,178154975,1614909622000,178154975
16,1.290,-0.103183,0.0107,121.420,2021-03-05,121.420,121.9350,117.5700,120.98,153766601,...,120.98,,AAPL,121.420,121.9350,117.5700,120.98,153766601,1614996964000,153766601
17,-5.060,-0.140557,-0.0417,116.360,2021-03-08,116.360,121.0000,116.2100,120.93,154376610,...,120.93,,AAPL,116.360,121.0000,116.2100,120.93,154376610,1615256169000,154376610
18,4.725,-0.105658,0.0406,121.085,2021-03-09,121.085,122.0600,118.7900,119.03,129525780,...,119.03,,AAPL,121.085,122.0600,118.7900,119.03,129525780,1615340881000,129525780

In [30]:
params = {'token': token,
          '_range': '1m'}

endpoint = '/stock/AAPL/news'
apple_news = requests.get(base_url+endpoint, params=params)

In [31]:
df = pd.DataFrame(apple_news.json())

df.head()

,datetime,hasPaywall,headline,image,lang,related,source,summary,url
0,1615358553000,False,Apple to Start Making iPhone 12 in India? Foxc...,https://cloud.iexapis.com/v1/news/image/769d5f...,en,AAPL,CNN-News18,Cupertino-based giant Apple will soon start ma...,https://cloud.iexapis.com/v1/news/article/769d...
1,1615356441811,False,Samsung to pip Apple in Q1 2021 smartphone pro...,https://cloud.iexapis.com/v1/news/image/57d7dc...,en,AAPL,Sify.com,Seoul: Riding on its flagship Galaxy S21 serie...,https://cloud.iexapis.com/v1/news/article/57d7...
2,1615354699000,False,Tesla-Aktien über Nacht um 20 Prozent gestiegen,https://cloud.iexapis.com/v1/news/image/531426...,de,AAPL,KURIER Medienhaus,Tesla-Aktien erzielten größten Tagesgewinn sei...,https://cloud.iexapis.com/v1/news/article/5314...
3,1615353483000,False,N.H. man credits Apple watch with saving his l...,https://cloud.iexapis.com/v1/news/image/fe182d...,en,AAPL,Tech Fans,N.H. man credits Apple watch with saving his l...,https://cloud.iexapis.com/v1/news/article/fe18...
4,1615353268000,False,News24.com | Thousands of startups file compla...,https://cloud.iexapis.com/v1/news/image/c7bc1d...,en,AAPL,News24,A group representing 2 000 French startups fil...,https://cloud.iexapis.com/v1/news/article/c7bc...

In [40]:
params = {'token': token,
          'from' : 2019}

apple_financials = requests.get(base_url+'/time-series/reported_financials/AAPL/10-Q', params=params)

apple_financials

In [44]:
df = pd.DataFrame(apple_financials.json())

df.head()

,AccountsPayableCurrent,AccountsReceivableNetCurrent,AccruedIncomeTaxesNoncurrent,AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment,AccumulatedOtherComprehensiveIncomeLossNetOfTax,AllocatedShareBasedCompensationExpense,AmendmentFlag,AmountUtilizedUnderShareRepurchaseProgram,AntidilutiveSecuritiesExcludedFromComputationOfEarningsPerShareAmount,Assets,...,id,irsNumber,key,periodEnd,periodStart,reportLink,subkey,update,updated,version
0,44293000000,18077000000,30948000000,51929000000,-3588000000,1559000000,NaN,37300000000,28800000.0,373719000000,...,REPORTED_FINANCIALS,NaN,AAPL,1546214400000,1.538352e+12,https://www.sec.gov/Archives/edgar/data/000032...,10-Q,NaN,1581627329000,us-gaap
1,30443000000,15085000000,30986000000,54290000000,-1499000000,1514000000,NaN,61300000000,30000000.0,341998000000,...,REPORTED_FINANCIALS,NaN,AAPL,1553990400000,1.546301e+12,https://www.sec.gov/Archives/edgar/data/000032...,10-Q,NaN,1581627463000,us-gaap
2,29115000000,14148000000,30521000000,56348000000,-639000000,4569000000,NaN,78200000000,20500000.0,322239000000,...,REPORTED_FINANCIALS,NaN,AAPL,1561852800000,1.554077e+12,https://www.sec.gov/Archives/edgar/data/000032...,10-Q,NaN,1581627528000,us-gaap
3,45111000000,20970000000,28198000000,60959000000,-418000000,1710000000,NaN,116100000000,28800000.0,340618000000,...,REPORTED_FINANCIALS,NaN,AAPL,1577750400000,1.569888e+12,https://www.sec.gov/Archives/edgar/data/000032...,10-Q,NaN,1596650349000,us-gaap
4,32421000000,15722000000,28188000000,62854000000,-2789000000,3407000000,NaN,134600000000,30000000.0,320400000000,...,REPORTED_FINANCIALS,NaN,AAPL,1585612800000,1.569888e+12,https://www.sec.gov/Archives/edgar/data/000032...,10-Q,NaN,1596650429000,us-gaap